apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdeployment
  labels:
    app: aksdeployment
  namespace: expressapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksdeployment
  template:
    metadata:
      labels:
        app: aksdeployment
    spec:
      containers:
        - name: aksdeployment
          image: rifielus.azurecr.io/expressapp1:latest
          ports:
            - containerPort: 3000