apiVersion: v1
kind: Service
metadata:
  name: aksdeployment
  namespace: namespace-workflow-1695127301680
spec:
  type: LoadBalancer
  selector:
    app: aksdeployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000