apiVersion: v1
kind: Service
metadata:
  name: buildleixoes
  namespace: leixoes
spec:
  type: LoadBalancer
  selector:
    app: buildleixoes
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000