apiVersion: v1
kind: Service
metadata:
  name: aksdeployment
  namespace: expressapp
spec:
  type: LoadBalancer
  selector:
    app: aksdeployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
